sudo: required
dist: trusty
language: fortran

matrix:
  include:
    - os: linux
      compiler: clang
      env: BTYPE=Release
    - os: linux
      compiler: gcc
      env: BTYPE=Release
    - os: osx
      compiler: gcc
      env: BTYPE=Release

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install gfortran; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc; fi

script:
  # Build
  - make
